#!/bin/bash

PORT="/dev/ttyACM0"
BAUD=115200

while true; do
    if [ -e "$PORT" ]; then
        echo "Device connected. Starting screen..."
        screen "$PORT" $BAUD

        echo "Screen exited or device removed. Waiting..."
    else
        clear
        echo "Waiting for $PORT..."
        sleep 1
    fi
    sleep 1
done
