#!/bin/bash

DEVICE="/dev/ttyACM0"
BAUD=115200

while true; do
    if [ -e "$DEVICE" ]; then
        echo "Device connected. Starting screen..."
        screen "$DEVICE" $BAUD

        echo "Screen exited or device removed. Waiting..."
    else
        clear
        echo "Waiting for $DEVICE..."
        sleep 1
    fi
    sleep 1
done
